services:
  # Next.js Application
  app:
    build: .
    container_name: notes-bookmarks-app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
